
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 

    command: /bin/sh -c "while sleep 1000; do :; done"
 
